language: java
sudo: required
jdk:
  - oraclejdk7
deploy:
  edge: true
  provider: script
  script: scripts/TestScript.sh
  on:
    branch: master 
env:
  - TRAVIS_BUILD_DIR="/home/travis/build/shrinidhi-atmakur/mytest"
  
